% MTLReg(1, 1) = struct(...
%     'Name', 'Air-Foil-Self-Noise',...
%     'Data', airfoilselfnoise,...
%     'Instances', 1503,...
%     'Attributes', 5,...
%     'Output', 6);
% MTLReg(2, 1) = struct(...
%     'Name', 'Concrete-Compressive-Strength',...
%     'Data', ConcreteData,...
%     'Instances', 1030,...
%     'Attributes', 8,...
%     'Output', 9);
Poly = Curve( 999, 4 );