% MTLReg(1, 1) = struct(...
%     'Name', 'Air-Foil-Self-Noise',...
%     'Data', airfoilselfnoise,...
%     'Instances', 1503,...
%     'Attributes', 5,...
%     'Output', 6);
% MTLReg(2, 1) = struct(...
%     'Name', 'Concrete-Compressive-Strength',...
%     'Data', ConcreteData,...
%     'Instances', 1030,...
%     'Attributes', 8,...
%     'Output', 9);
% Poly = Curve( 399, 4 );

% 初始化参数表
% load('LabIParams.mat');
% nParams = length(IParams);
% for i = 1 : nParams
%     nParams = GetParamsCount(IParams{i});
%     Method = IParams{i};
%     tic
%     Params = GetParams(Method, 1);
%     Time = toc;
%     fprintf('%s:%d params %.2f.\n', Method.Name, nParams, nParams*Time);
% end