% 数据集名称
Names = {
    'Ecoli',...
    'Abalone', 'Adult', 'Mushroom', 'Car Evaluation', 'Glass',...
    'Hepatocellular Carcinoma Dataset (HCC dataset)', 'Poker Hand',...
    'wine', 'Immunotherapy', 'wine-quality-red', 'wine-quality-white', 'wifilocalization', ...
    'Aggregation', 'Compound', 'Pathbased', 'Spiral', 'D31', 'R15', 'Jain', 'Flame', 'Star',...
    'Sine', 'Grid', 'Ring'
};
% 数据集
Datasets = {
%    ecoli...
%    abalone, adult, agaricuslepiota, car, glass, hccdata, pokerhandtrainingtrue
%    wine, Immunotherapy, winequalityred, winequalitywhite, wifilocalization,...
%    Aggregation, Compound, Pathbased, Spiral, D31, R15, Jain, Flame, Star,...
%    Sine, Grid, Ring
};
% 数据集标签所在列
LabelColumn = [
    9,...
    9, 15, 23, 7, 10, 50, 11,...
    1, 8, 12, 12, 8,...
    3, 3, 3, 3, 3, 3, 3, 3, 3,...
    3, 3, 3
];
% 数据集分类数
Classes = [
    8,...
    29, 2, 23, 4, 7, 2, 10,...
    3, 2, 6, 7, 4,...
    7, 6, 3, 3, 31, 15, 2, 2, 5,...
    2, 2, 2
];

% 打包数据集
for i = 1 : 12
    [Instances, Attributes] = size(Datasets{i});
    Lab(i) = PackDataset(Names{i}, Datasets{i}, LabelColumn(i), Classes(i), Instances, Attributes-1, '', []);
end